### ISSUE TITLE
Add flag to include dev dependencies

### ISSUE THREAD

**Issue by gergo-papp** [dschniepp/kudos#11]
I recently made a change in #6  so that only production dependencies (and their children dependencies) are included.

Even if it's uncommon, some users might still want to generate license info with dev dependencies included, so the main reason for creating this issue is to keep track of this behavior.

We could add a flag and allow including these deps as well, for example:
```bash
mix kudos.generate --include-dev
```

**Comment by dschniepp** [comment]
I added the flag as `--include-dev-deps` see #12.
