### ISSUE TITLE
never work with elixir please help

### ISSUE THREAD

**Issue by alexgocariq** [dschniepp/kudos#14]
I need to scan dependencies for different project like java gradle/maven, python, go does this elixir tools scans those?
Also how I can run it against the project documentation is not sufficient could you provide more concrete steps

**Comment by dschniepp** [comment]
No, this only works for elixir and hex based projects, but there should be similar tools available for other languages and package managers.

**Comment by alexgocariq** [comment]
Thanks that's what I understood as well.
